export const NUL = '\x00' // Null character
const C01 = '\x01' // Start of Heading
const C02 = '\x02' // Start of Text
export const ETX = '\x03' // End of Text (ctrl+c)
const C04 = '\x04' // End of Transmission
const C05 = '\x05' // Enquiry
const C06 = '\x06' // Acknowledge
const C07 = '\x07' // Bell, Alert
const C08 = '\x08' // Backspace
const C09 = '\x09' // Horizontal Tab
export const LF = '\x0A' // Line Feed
const C0B = '\x0B' // Vertical Tabulation
const C0C = '\x0C' // Form Feed
export const CR = '\x0D' // Carriage Return
const C0E = '\x0E' // Shift Out
const C0F = '\x0F' // Shift In
const C10 = '\x10' // Data Link Escape
const C11 = '\x11' // Device Control One (XON)
const C12 = '\x12' // Device Control Two
const C13 = '\x13' // Device Control Three (XOFF)
const C14 = '\x14' // Device Control Four
const C15 = '\x15' // Negative Acknowledge
const C16 = '\x16' // Synchronous Idle
const C17 = '\x17' // End of Transmission Block
const C18 = '\x18' // Cancel
const C19 = '\x19' // End of medium
const C1A = '\x1A' // Substitute
export const ESC = '\x1B' // Escape
const C1C = '\x1C' // File Separator
const C1D = '\x1D' // Group Separator
const C1E = '\x1E' // Record Separator
const C1F = '\x1F' // Unit Separator
export const SPC = '\x20' // Space
export const DEL = '\x7F' // Delete
